export interface UserModel {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  gender: string;
  skills: string;
  imageUrl: string;
}

export const usersData: UserModel[] = [
  {
    id: 1,
    first_name: "Bennett",
    last_name: "Cattonnet",
    email: "bcattonnet0@4shared.com",
    gender: "Male",
    skills: "graphic design",
    imageUrl: "http://dummyimage.com/233x100.png/5fa2dd/ffffff",
  },
  {
    id: 2,
    first_name: "Daryn",
    last_name: "Burger",
    email: "dburger1@yandex.ru",
    gender: "Female",
    skills: "photography",
    imageUrl: "http://dummyimage.com/103x100.png/dddddd/000000",
  },
  {
    id: 3,
    first_name: "Kienan",
    last_name: "Gosforth",
    email: "kgosforth2@technorati.com",
    gender: "Male",
    skills: "time management",
    imageUrl: "http://dummyimage.com/249x100.png/cc0000/ffffff",
  },
  {
    id: 4,
    first_name: "Lorena",
    last_name: "Gritton",
    email: "lgritton3@washington.edu",
    gender: "Female",
    skills: "SEO optimization",
    imageUrl: "http://dummyimage.com/231x100.png/ff4444/ffffff",
  },
  {
    id: 5,
    first_name: "Stillmann",
    last_name: "De Robertis",
    email: "sderobertis4@ning.com",
    gender: "Male",
    skills: "project management",
    imageUrl: "http://dummyimage.com/233x100.png/5fa2dd/ffffff",
  },
  {
    id: 6,
    first_name: "Evangeline",
    last_name: "Tabourel",
    email: "etabourel5@census.gov",
    gender: "Female",
    skills: "data analysis",
    imageUrl: "http://dummyimage.com/129x100.png/ff4444/ffffff",
  },
  {
    id: 7,
    first_name: "Aldin",
    last_name: "Mulchrone",
    email: "amulchrone6@parallels.com",
    gender: "Male",
    skills: "photography",
    imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
  },
  {
    id: 8,
    first_name: "Win",
    last_name: "Hambling",
    email: "whambling7@independent.co.uk",
    gender: "Male",
    skills: "social media marketing",
    imageUrl: "http://dummyimage.com/225x100.png/cc0000/ffffff",
  },
  {
    id: 9,
    first_name: "Torre",
    last_name: "Benn",
    email: "tbenn8@hhs.gov",
    gender: "Male",
    skills: "social media marketing",
    imageUrl: "http://dummyimage.com/246x100.png/5fa2dd/ffffff",
  },
  {
    id: 10,
    first_name: "Ingemar",
    last_name: "Millier",
    email: "imillier9@upenn.edu",
    gender: "Male",
    skills: "SEO optimization",
    imageUrl: "http://dummyimage.com/213x100.png/ff4444/ffffff",
  },
  {
    id: 11,
    first_name: "Phylys",
    last_name: "Suart",
    email: "psuarta@yellowbook.com",
    gender: "Female",
    skills: "video editing",
    imageUrl: "http://dummyimage.com/236x100.png/5fa2dd/ffffff",
  },
  {
    id: 12,
    first_name: "Berkley",
    last_name: "Dikelin",
    email: "bdikelinb@wsj.com",
    gender: "Male",
    skills: "SEO optimization",
    imageUrl: "http://dummyimage.com/207x100.png/dddddd/000000",
  },
  {
    id: 13,
    first_name: "Amandi",
    last_name: "Rown",
    email: "arownc@hao123.com",
    gender: "Female",
    skills: "video editing",
    imageUrl: "http://dummyimage.com/128x100.png/dddddd/000000",
  },
  {
    id: 14,
    first_name: "Denney",
    last_name: "Beevens",
    email: "dbeevensd@mediafire.com",
    gender: "Male",
    skills: "leadership",
    imageUrl: "http://dummyimage.com/120x100.png/cc0000/ffffff",
  },
  {
    id: 15,
    first_name: "Roosevelt",
    last_name: "Portriss",
    email: "rportrisse@fc2.com",
    gender: "Male",
    skills: "video editing",
    imageUrl: "http://dummyimage.com/142x100.png/ff4444/ffffff",
  },
  {
    id: 16,
    first_name: "Linn",
    last_name: "Kiezler",
    email: "lkiezlerf@github.com",
    gender: "Female",
    skills: "time management",
    imageUrl: "http://dummyimage.com/103x100.png/cc0000/ffffff",
  },
  {
    id: 17,
    first_name: "Haslett",
    last_name: "Godbald",
    email: "hgodbaldg@vistaprint.com",
    gender: "Male",
    skills: "financial planning",
    imageUrl: "http://dummyimage.com/182x100.png/cc0000/ffffff",
  },
  {
    id: 18,
    first_name: "Thaine",
    last_name: "Buckston",
    email: "tbuckstonh@msn.com",
    gender: "Male",
    skills: "event planning",
    imageUrl: "http://dummyimage.com/210x100.png/5fa2dd/ffffff",
  },
  {
    id: 19,
    first_name: "Shurwood",
    last_name: "Zuker",
    email: "szukeri@vk.com",
    gender: "Male",
    skills: "event planning",
    imageUrl: "http://dummyimage.com/221x100.png/dddddd/000000",
  },
  {
    id: 20,
    first_name: "Rodolphe",
    last_name: "Grishelyov",
    email: "rgrishelyovj@miitbeian.gov.cn",
    gender: "Male",
    skills: "problem solving",
    imageUrl: "http://dummyimage.com/167x100.png/5fa2dd/ffffff",
  },
  {
    id: 21,
    first_name: "Brandea",
    last_name: "Lambourn",
    email: "blambournk@accuweather.com",
    gender: "Female",
    skills: "leadership",
    imageUrl: "http://dummyimage.com/237x100.png/ff4444/ffffff",
  },
  {
    id: 22,
    first_name: "Antonio",
    last_name: "Harlow",
    email: "aharlowl@nih.gov",
    gender: "Male",
    skills: "photography",
    imageUrl: "http://dummyimage.com/166x100.png/dddddd/000000",
  },
  {
    id: 23,
    first_name: "Kin",
    last_name: "Shevlin",
    email: "kshevlinm@people.com.cn",
    gender: "Male",
    skills: "event planning",
    imageUrl: "http://dummyimage.com/143x100.png/cc0000/ffffff",
  },
  {
    id: 24,
    first_name: "Sampson",
    last_name: "Kohnen",
    email: "skohnenn@netscape.com",
    gender: "Male",
    skills: "SEO optimization",
    imageUrl: "http://dummyimage.com/166x100.png/cc0000/ffffff",
  },
  {
    id: 25,
    first_name: "Wade",
    last_name: "Westman",
    email: "wwestmano@imgur.com",
    gender: "Male",
    skills: "web development",
    imageUrl: "http://dummyimage.com/182x100.png/cc0000/ffffff",
  },
  {
    id: 26,
    first_name: "Oswald",
    last_name: "Wakeley",
    email: "owakeleyp@newsvine.com",
    gender: "Male",
    skills: "creative writing",
    imageUrl: "http://dummyimage.com/183x100.png/cc0000/ffffff",
  },
  {
    id: 27,
    first_name: "Siward",
    last_name: "Stean",
    email: "ssteanq@ucsd.edu",
    gender: "Genderqueer",
    skills: "foreign language proficiency",
    imageUrl: "http://dummyimage.com/214x100.png/ff4444/ffffff",
  },
  {
    id: 28,
    first_name: "Zachary",
    last_name: "Darridon",
    email: "zdarridonr@nps.gov",
    gender: "Male",
    skills: "web development",
    imageUrl: "http://dummyimage.com/223x100.png/dddddd/000000",
  },
  {
    id: 29,
    first_name: "Starr",
    last_name: "Loggie",
    email: "sloggies@w3.org",
    gender: "Female",
    skills: "project management",
    imageUrl: "http://dummyimage.com/206x100.png/ff4444/ffffff",
  },
  {
    id: 30,
    first_name: "Paton",
    last_name: "Foli",
    email: "pfolit@comsenz.com",
    gender: "Male",
    skills: "problem solving",
    imageUrl: "http://dummyimage.com/119x100.png/ff4444/ffffff",
  },
];
